### ISSUE TITLE
Metadata json update

### ISSUE THREAD

**Issue by robertpiosik** [cedvdb/dart_phone_metadata#4]
Hi, thanks for the package :)

I have kind request to update the metadata json - it's 8 months old and we got some new providers in Philippines that aren't supported by the current version.

Thank you!

**Comment by cedvdb** [comment]
Hello, 

If you want to do it yourself:

There is the `/resource` directory with a readme inside it. The readme describes how to convert the metadata found in the repository phonenumberkit for ios to the metadata.json parsable by this repository. Then there is another command (the first one in the readme) to generate the Dart code.  So basically you just need to get the correct json from the other repo, replace the old one, run the two commands and make a PR.

This week I'm already full

**Comment by cedvdb** [comment]
It's updated here but not yet in the phone_numbers_parser library, as it seems some tests are failing there. Some example phone numbers that were used previously are now invalid, probably invalid before too but were passing. I'll fix that tomorrow by generating examples from the metadata

**Comment by cedvdb** [comment]
Actually did it tonight, v5.0.3 of phone_numbers_parser and metadata updated.
