### ISSUE TITLE
Please Update, libphonenumber v8.12.52 released July 19, 2022

### ISSUE THREAD

**Issue by ooglek** [cedvdb/dart_phone_metadata#5]
Thanks!

**Comment by cedvdb** [comment]
the metadata repository is in my account somewhere, there is a script to be run that regenerates the metadata. I'm pretty busy right now, but I'll review a PR

**Comment by cedvdb** [comment]
Is there a problem doing it ?

Here is the folder in question: https://github.com/cedvdb/dart_phone_metadata/tree/main/resources

the metadata used is the json from the ios library that already convert the xml metadata from google to json format. The file to be replaced is original_phone_metadata.json

Here is the repository, it was updated with latest metadata not long ago: https://github.com/marmelroy/PhoneNumberKit/tree/master/PhoneNumberKit/Resources

**Comment by ooglek** [comment]
I can take a look and see if I can automate it. If I pull a PR, I may include documentation on how to update this repo. 

I wanted to open an issue in case you prefer to manage it yourself and are not a fan of PRs for such things. If you're OK with a PR, I can try to update.

**Comment by cedvdb** [comment]
Yes PRs are encouraged (I should have put a better readme in place too as you said). The metadata from this library is used: 

https://github.com/marmelroy/PhoneNumberKit/tree/master/PhoneNumberKit/Resources

this library has a script update.sh. This script takes the original google xml file and convert it to json. What is done here is copying that json file into the lib and then running our own script to transform the json from phonenumberkit to our own json.

So it's effectively going three hoops:  google-metadata.xml -> phone-number-kit.json -> phone_metadata-dart.json.

This makes this library reliant on phone-number-kit keeping up to date with google-metadata. We could copy their script here and use the google metadata directly too, or just keep doing like it's done currently.

Note: if you navigate to this library (dart_phone_metadata) resource folder there is a readme but it's concise.

**Comment by ooglek** [comment]
Done! PR submitted. I updated the `README.md` with a bit of a more detailed process you outlined above. Hope that's useful!
